Repository provectus/swiss-army-kube, pull requests merged in 2020-09, with the labels that each got.

#97 Fix/budge
  README.md
Labels: skip-changelog

#98 fix worker group az count
  example/example.tfvars
  example/main.tf
  modules/kubernetes/local.tf
  modules/kubernetes/variables.tf
Labels: bug

#99 fix kubelet_extra_args register-with-taints arguments
  modules/kubernetes/local.tf
Labels: bug

#101 Add HPA module
  CONTRIBUTING.md
  docs/CONTRIBUTE_PR.md
  modules/scaling/README.md
  modules/scaling/cluster-autoscaler.tf
  modules/scaling/hpa.tf
  modules/scaling/main.tf
  modules/scaling/variables.tf
  modules/scaling/versions.tf
Labels: enhancement
