Repository provectus/swiss-army-kube, pull requests merged in 2021-03, with the labels that each got.

#136 Feature/cert manager
  modules/scaling/README.md
  modules/system/cert-manager/README.md
  modules/system/cert-manager/main.tf
  modules/system/cert-manager/variables.tf
Labels: enhancement

#166 change module source to github repo
  examples/argocd-with-applications/main.tf
  examples/argocd/main.tf
  examples/argoproj/main.tf
  examples/common/main.tf
Labels: enhancement

#164 Private repository support for ArgoCD
  modules/cicd/argo/modules/cd/README.md
  modules/cicd/argo/modules/cd/main.tf
  modules/cicd/argo/modules/cd/variables.tf
Labels: enhancement

#152 Add cognito users module
  modules/cognito/README.md
  modules/cognito/output.tf
  modules/cognito/user-pool/README.md
  modules/cognito/user-pool/main.tf
  modules/cognito/user-pool/output.tf
  modules/cognito/user-pool/variables.tf
  modules/cognito/users/main.tf
  modules/cognito/users/output.tf
  modules/cognito/users/variables.tf
  modules/cognito/variables.tf
Labels: enhancement, help wanted

#153 add kfserving as module (YAML specs for argo-cd Application)
  modules/kfserving/0-3-0/locals.tf
  modules/kfserving/0-3-0/main.tf
  modules/kfserving/0-3-0/variables.tf
Labels: enhancement

#154 add kube2iam module (YAML spec creation for argocd)
  modules/system/kube2iam/locals.tf
  modules/system/kube2iam/main.tf
  modules/system/kube2iam/variables.tf
Labels: enhancement

#155 Update kubernetes module by:
  modules/kubernetes/local.tf
  modules/kubernetes/main.tf
  modules/kubernetes/outputs.tf
  modules/kubernetes/variables.tf
Labels: enhancement

#156 add mlflow as module (YAML specs for argo-cd Application)
  modules/mlflow/locals.tf
  modules/mlflow/main.tf
  modules/mlflow/variables.tf
Labels: enhancement, help wanted

#157 add kubeflow profiles as module (YAML specs for argo-cd Application)
  modules/kubeflow-profiles/main.tf
  modules/kubeflow-profiles/variables.tf
Labels: enhancement

#158 add s3 storage module (meant for Kubeflow artifact storage)
  modules/storage/s3/main.tf
  modules/storage/s3/output.tf
  modules/storage/s3/variables.tf
Labels: enhancement

#159 Update rds module by:
  modules/rds/main.tf
  modules/rds/output.tf
  modules/rds/variables.tf
Labels: enhancement

#160 update network module by:
  modules/network/local.tf
  modules/network/main.tf
  modules/network/variables.tf
Labels: bug

#161 add kubeflow-operator module
  modules/kubeflow-operator/locals.tf
  modules/kubeflow-operator/main.tf
  modules/kubeflow-operator/variable.tf
Labels: enhancement

#162 Feature/argocd module
  modules/cicd/argo-cd/main.tf
  modules/cicd/argo-cd/output.tf
  modules/cicd/argo-cd/variables.tf
Labels: enhancement

#170 Update examples
  .github/workflows/reviewdog.yml
  examples/argocd-with-applications/README.md
  examples/argocd-with-applications/main.tf
  examples/argocd/main.tf
  examples/argocd/variables.tf
  examples/argocd/versions.tf
  examples/argoproj/.terraform.lock.hcl
  examples/argoproj/main.tf
  examples/argoproj/versions.tf
  examples/common/.terraform.lock.hcl
  examples/common/README.md
  examples/common/main.tf
  examples/common/variables.tf
  jenkinsfile
Labels: enhancement
